/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.55
 * Generated at: 2015-04-25 05:25:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Women Safety Portal</title>\r\n");
      out.write("\t<meta name=\"keywords\" content=\"\" />\r\n");
      out.write("\t<meta name=\"description\" content=\"\" />\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("\t<meta name=\"viewport\" content=\"initial-scale=1\">\r\n");
      out.write("    \r\n");
      out.write("\t<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/font-awesome.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/templatemo_misc.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"css/templatemo_style.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//cdn.datatables.net/plug-ins/1.10.6/integration/bootstrap/3/dataTables.bootstrap.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"main-sidebar\" class=\"hidden-xs hidden-sm\">\r\n");
      out.write("\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t<a href=\"#\"><h1>Women Safety</h1></a>\r\n");
      out.write("\t\t\t<span>the women safety portal</span>\r\n");
      out.write("\t\t</div> <!-- /.logo -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div >\r\n");
      out.write("\t        <ul class=\"main-menu\">\r\n");
      out.write("\t            <li class=\"home\"><a href=\"#home\">Requests</a></li>\r\n");
      out.write("\t            <li class=\"portfolio\"><a href=\"#users\">Users</a></li>\r\n");
      out.write("\t            <li class=\"portfolio\"><a href=\"Logout\">Logout</a></li>\r\n");
      out.write("\t        </ul>\r\n");
      out.write("\t\t</div> <!-- /.navigation -->\r\n");
      out.write("\r\n");
      out.write("\t</div> <!-- /#main-sidebar -->\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"main-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div id=\"home\" class=\"section-content\">\r\n");
      out.write("\t\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"welcome-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Recent Request Occured</h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"main-slider\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<table id=\"requests\"\r\n");
      out.write("\t\t\t\t\tclass=\"table  table-striped table-bordered\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Mobile No</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>IMEI</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Latitude</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Longitude</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Address</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Done ?</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div> <!-- /#sTop -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"users\" class=\"section-content\">\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"section-title\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"welcome-text\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>Registered Users</h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"main-slider\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t\t<table id=\"user\"\r\n");
      out.write("\t\t\t\t\tclass=\"table  table-striped table-bordered\" cellspacing=\"0\" width=\"100%\">\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Name</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Mobile No</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Parent No</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Voter Id</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>IMEI</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Postal Code</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Email Id</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>Address</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div> <!-- /#about -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t</div> <!-- /.container-fluid -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"site-footer\">\r\n");
      out.write("\t\t\t<div class=\"bottom-footer\">\r\n");
      out.write("\t\t\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"copyright\">Copyright © 2014 <a href=\"#\">Women Safety Portal</a>\r\n");
      out.write("                            </p>\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /.col-md-6 -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 credits\">\r\n");
      out.write("\t\t\t\t\t\t\t<p>by <a rel=\"nofollow\" href=\"https://www.facebook.com/teamandappers\">TeamAndAppers</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div> <!-- /.col-md-6 -->\r\n");
      out.write("\t\t\t\t\t</div> <!-- /.row -->\r\n");
      out.write("\t\t\t\t</div> <!-- /.container-fluid -->\r\n");
      out.write("\t\t\t</div> <!-- /.bottom-footer -->\r\n");
      out.write("\t\t</div> <!-- /.site-footer -->\r\n");
      out.write("\r\n");
      out.write("\t</div> <!-- /#main-content -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- JavaScripts -->\r\n");
      out.write("\t<script src=\"//code.jquery.com/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.singlePageNav.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.flexslider.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery.prettyPhoto.js\"></script>\r\n");
      out.write("\t<script src=\"js/custom.js\"></script>\r\n");
      out.write("\t<script src=\"//cdn.datatables.net/1.10.6/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t<script src=\"//cdn.datatables.net/plug-ins/1.10.6/integration/bootstrap/3/dataTables.bootstrap.js\"></script>\r\n");
      out.write("\t<script src=\"js/index.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t$(\"a[data-gal^='prettyPhoto']\").prettyPhoto({hook: 'data-gal'});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("        function initialize() {\r\n");
      out.write("          var mapOptions = {\r\n");
      out.write("            zoom: 11,\r\n");
      out.write("            center: new google.maps.LatLng(16.8451789,96.1439764)\r\n");
      out.write("          };\r\n");
      out.write("\r\n");
      out.write("          var map = new google.maps.Map(document.getElementById('map-canvas'),\r\n");
      out.write("              mapOptions);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function loadScript() {\r\n");
      out.write("          var script = document.createElement('script');\r\n");
      out.write("          script.type = 'text/javascript';\r\n");
      out.write("          script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&' +\r\n");
      out.write("              'callback=initialize';\r\n");
      out.write("          document.body.appendChild(script);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        window.onload = loadScript;\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
